name: 'epic-tasks-action'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  githubToken:
    required: true
    description: 'A github token with permissions to update issues'
runs:
  using: 'node12'
  main: 'dist/index.js'
