name: 'demo'
on:
  issues:
    types:
      - closed
      - edited
      - labeled
      - opened
      - unlabeled
      - deleted
      - reopened
  issue_comment:
    types: [created, deleted]

jobs:
  epic-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: Finkes/epic-tasks-action@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
