name: 'build-test'
on:
  issues:
    types:
      - closed
      - edited
      - labeled
      - opened
      - unlabeled
      - deleted
      - reopened
  issue_comment:
    types: [created, deleted]

jobs:
  epic-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: Finkes/epic-tasks-action
        with:
          - githubToken: "todo"